### ISSUE TITLE
Edit content in Are you named in lawsuit page after selecting wage garnishment

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#15]
The are you named in the lawsuit text is the same for wage garnishment and levy.  So if I selected I got a wage garnishment it has this explanatory text in are you named in the lawsuit:

"In some cases, you might be sent a notice of a levy if you are not the person named in a lawsuit, but that person is believed to have some interest in your property, such as a shared bank account. If you are NOT the person named in the lawsuit, click “no” below."   

Either a new page just for wage garnishment needs to be created or this needs to be generic to apply to all situations.

**Comment by EricNakano** [comment]
Made question generic to apply to either.
