### ISSUE TITLE
Content in how notice sent for Notice of Levy Not for Bank is about a bank account

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#17]
If you select "I received a levy for something other than a bank account" the next pages talk about bank accounts:

Was your Notice of Levy sent by mail?
When your bank account is frozen by a creditor, that is called a “bank levy.” A form called a Notice of Levy is typically mailed, but in occasionally given to you in person.

Did you receive a notice in the mail?

**Comment by EricNakano** [comment]
Made text generic to apply to bank account or other levy.
