### ISSUE TITLE
Wont let you move fwd without e-sign

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#18]
When I click "continue" on signature page nothing happens unless I e-sign

**Comment by EricNakano** [comment]
This requires community.lawyer to fix.

**Comment by kfstieler** [comment]
are they fixing it?

**Comment by EricNakano** [comment]
I just chatted with them, and it's less a bug than a feature... A workaround is to create a question block that asks if you want to digitally sign and then conditionally display the signature block. I will go ahead and implement this after-hours.

**Comment by EricNakano** [comment]
A new question asks if you wish to sign on the computer.
