### ISSUE TITLE
Select on Received Notice of Judgment or I havent rcvd any notices it goes to e-signature page not info on judgment

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#19]
I selected only that I received a notice of judgment and it goes right to e-signature page.  When I sign it says thanks for using this application.  It should go to info about a judgment not signature page

**Comment by EricNakano** [comment]
The error is because there is no Final page for this condition. Because of this, the logic of the program continues until it reaches the signature page. A new final block needs to be added to deal with this condition, and the language of the block needs to be written.

**Comment by EricNakano** [comment]
Resolved.
