### ISSUE TITLE
Set aside link goes to dead JCC prelive link

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#20]
On this page: Exiting as deadline passed

the "here" links go to jccprelive-open cities - https://jcc.prelive.opencities.com/Alpha-Services/Consumer-Debt

"More information that may help protect your money or property in the future can be found here."

"Go here to learn more about setting aside a judgment."

**Comment by EricNakano** [comment]
Removed link.
