### ISSUE TITLE
Hardship Information 

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#31]
Do we need to have the additional question asking if there wants to be an attachment. Can we just have some logic that adds the attachment if the character limit goes over?

**Comment by EricNakano** [comment]
This would be nice. Did not initially do due to the time constraint of adding additional logic. Logic would probably consist of a character number that if it is under it prints on the main form, if it is over, it prints on the attachment instead, and prints "See attachment" on the main page.
