### ISSUE TITLE
Page 1 - yes/no go to wrong page

### ISSUE THREAD

**Issue by kfstieler** [JudicialCouncilOfCalifornia/docassemble.jcc.debtdefense#33]
https://jackmadans.community.lawyer/interview?i=docassemble.playground1%3AOj5nE3fNvaozt4B6.yml#page1

logic set-up wrong.  when select "no" I dont want and explanation it goes to explanation; select "yes" want explanation it doesn't give one.

**Comment by EricNakano** [comment]
Corrected.
